---
- name: 'Instalar Zabbix Agent2'
  hosts: all
  # remote_user: herzer
  # become: yes

  vars:
    zabbix_server_ip: "172.31.253.150"
    zabbix_server_port: 10050
    AL8: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
    AL9: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm

  tasks:

    - name: 'Configura o Zabbix Agent no Almalinux 8'
      block:

        - name: 'Configura o Repositório Oficial do Zabbix'
          ansible.builtin.yum:
            name: "{{ AL8 }}"
            state: present
            disable_gpg_check: yes

        # - name: 'Checa se o repo EPEL está presente'
        #   ansible.builtin.stat:
        #     path: /etc/yum.repos.d/epel.repo
        #   register: epel

        - name: 'Instalar pacotes necessários'
          ansible.builtin.yum:
            name:
            disablerepo: epel
              - zabbix-agent
            state: present

        - name: 'Configurar o agente Zabbix'
          template:
            src: zabbix_agentd.conf.j2
            dest: /etc/zabbix/zabbix_agentd.conf

        - name: 'reiniciar serviço zabbix-agent'
          service:
            name: zabbix-agent
            enabled: yes
            state: restarted

      when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '8'

    - name: 'Configura o Zabbix Agent no Almalinux 9'
      block:

        - name: 'Configura o Repositório Oficial do Zabbix'
          ansible.builtin.yum:
            name: "{{ AL9 }}"
            state: present
            disable_gpg_check: yes

        # - name: 'Checa se o repo EPEL está presente'
        #   ansible.builtin.stat:
        #     path: /etc/yum.repos.d/epel.repo
        #   register: epel

        - name: 'Instalar pacotes necessários'
          ansible.builtin.yum:
            disablerepo: epel
            name:
              - zabbix-agent
            state: present

        - name: 'Configurar o agente Zabbix'
          template:
            src: zabbix_agentd.conf.j2
            dest: /etc/zabbix/zabbix_agentd.conf

        - name: 'reiniciar serviço zabbix-agent'
          service:
            name: zabbix-agent
            enabled: yes
            state: restarted

      when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'